# Generated by Django 4.0.4 on 2022-05-10 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_v1', '0002_alter_score_date_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ('-score', 'name')},
        ),
    ]
